# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    from_email: "%env(EMAIL_FROM)%"
    from_title: "%env(EMAIL_FROM_TITLE)%"
    exchange_rate_alert_email: "%env(EXCHANGE_RATE_ALERT_EMAIL)%"
    exchange_rate_alert_title: "%env(EXCHANGE_RATE_ALERT_TITLE)%"
    iso4217_file: "/config/currencies.json"

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    Symfony\Bridge\Twig\Mime\TemplatedEmail:
        public: true

    Symfony\Component\Mime\Address:
        class: Symfony\Component\Mime\Address
        arguments:
            - '%from_email%'
            - '%from_title%'
